- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend
details see this
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/291
> [OpenWebif] replace file remote control for dm8000

- meta-openpli/recipes-openpli/enigma2/hotplug-e2-helper.bb
modified:   meta-openpli/recipes-openpli/enigma2/hotplug-e2-helper.bb
> Changed hotplug-e2-helper.bb to last revision.

- meta-openpli/recipes-devtools/python/python-wifi_0.5.0.bb
> meta-openpli: python-wifi fix SRC_URI

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-xmltvimport.bb
Please do not forget update the plugin version sha to actual!
> Use distutils-openplugins for xmltvimport build to simplify bitbake file

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-youtube.bb
Use license file for checksum.
Set correct path to py files.
> Plugin youtube

- meta-openpli/recipes-core/busybox/busybox/mdev-mount.sh
sd mmc card use formuler and zgemma model
> mdev-mount.sh: add mout type mmc1 for /dev/mmcblk0p1

- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
> zip: add to feed

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-mountmanager.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
-Mount devices at your decision (label,uuid)
> Add plugin mountmanager

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-autobouquets.bb
- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-autobouquetsmaker.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
plugin on 3rd party feed is obselete. use current on github.
> Add plugin AutoBouquets E2 28.2e on feed

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-tmbd.bb
- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-xmodem.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
-Search the internet bases themoviedb.org/kinopoisk.ru
-plugin to connect to internet via any modems
> Add plugins tmbd and xmodem to feed

- meta-openpli/recipes-core/busybox/busybox/mdev-mount.sh
discussion here
http://forums.openpli.org/topic/41278-ssd-trim/?view=findpost&p=544398
> [mdev-mount.sh] add mount option noatime for all type filesystem

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-blurayplayer.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
- meta-openpli/recipes-support/libbluray/libbluray_git.bb
- meta-openpli/recipes-support/libudfread/libudfread_git.bb
Disable freetype.
Small optimization in bb file.
> Update libbluray on 0.9.3

- meta-openpli/recipes-openpli/enigma2/enigma2.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb
Sets e2 branch to master next
osdpositionsetup wizard works on all stb's
> Master for gcc5

- meta-openpli/recipes-openpli/openmultiboot/openmultiboot.bb
> add openmultiboot tools

- meta-openpli/recipes-multimedia/tuxbox/tuxbox-common.bb
Requires: https://github.com/OpenPLi/OpenPLi-1/pull/1
> tuxbox-common: Add atsc.xml to transponder lists

- meta-openpli/recipes-multimedia/astra-sm/astra-sm/undef_dvb_net.patch
- meta-openpli/recipes-multimedia/astra-sm/astra-sm/version.patch
- meta-openpli/recipes-multimedia/astra-sm/astra-sm_0.2.bb
- meta-openpli/recipes-multimedia/dvblast/dvblast.bb
- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
- meta-openpli/recipes-support/bitstream/bitstream.bb
- meta-openpli/recipes-support/libev/libev_4.22.bb
Astra (Advanced Streamer) is a professional software to organize Digital TV Service for TV operators and broadcasters, internet service providers, hotels, etc.
DVBlast is written to be the core of a custom IRD, CID, or ASI gateway, based on a PC with a Linux-supported card. It is very lightweight and stable, designed for 24/7 operation.
> Add astra-sm and dvblast utilities

- meta-openpli/recipes-core/initscripts/initscripts-1.0/umountfs
-sleep 5 sec. epg time to save
-sync to flush pending writes for loop-mounted file system
-add 'sdparm --command=stop /dev/sd?' for sleep hdd
> add local openpli file umountfs

- meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb
-this plugin old time not works
> delete enigma2-plugin-systemplugins-satscan in feed

- meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb
formuler:
https://github.com/formuler/meta-formuler/commit/d6b1d80e9fea5d2382712b513fbc06a23ee2d254
mutant:
https://github.com/HD-Digital/meta-hd/commit/e80b20a439d17493c643aba9c2e81f51877894c8
> add ci / 7seg for MACHINE_FEATURES

- meta-openpli/recipes-core/busybox/busybox/mdev-mount.sh
/sys/block/sda :
/sys/devices/platform/rdb/f045a000.sata/ata1/host0/target0:0:0/0:0:0:0
> [mdev-mount] add detection internal HDD format HD51

- meta-openpli/recipes-openpli/enigma2/enigma2.bb
h3: move plugin vfdcontrol from image to feed
Please use together with this: https://github.com/OpenPLi/enigma2/pull/607
> zgemma: update bsp

- meta-openpli/recipes-core/busybox/busybox/mdev.conf
Several new boxes support more than 4 vtuners
> mdev: support move vtuner devices

- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.inc
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-look-100x60_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-look-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/picons-enigma2-meta.bb
> picons: Add Stefan's Ziggo metal look 100x60 picons to feed.

- meta-openpli/recipes-extended/hddtemp/hddtemp/hddtemp.db
- meta-openpli/recipes-extended/hddtemp/hddtemp_0.3-beta15.bb
-Now we can add new HDD / SSD in a database
> [hddtemp] use its own file hddtemp.db

- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.black-white-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-look-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-stamp-100x60_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-stamp-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.reflection-black-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.transparent-white-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/picons-enigma2-meta.bb
-Metal-look-100x60
-Metal-look-220x132
-Metal-stamp-100x60
-Metal-stamp-220x132
-Black-white-220x132
-Reflection-black-220x132
-Transparent-white-220x132
Change url metal-look picons due to new github account.
> picons: Add Stefan's Ziggo picons to feed.

- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-100x60_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.metal-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/enigma2-plugin-picons-ziggo.transparent-black-220x132_git.bb
- meta-openpli/recipes-openpli/enigma2-picons/picons-enigma2-meta.bb
-Metal-100x60
-Metal-220x132
-Transparent-black-220x132
> Add more Ziggo picons to feed.

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-kodi_0.5.bb
Enigma2 plugin to launch and play media from Kodi
> Add Kodi Launcher Plugin

- meta-openpli/recipes-mediacenter/kodi/kodi/0001-configure-don-t-try-to-run-stuff-to-find-tinyxml.patch
- meta-openpli/recipes-mediacenter/kodi/kodi/0002-handle-SIGTERM.patch
- meta-openpli/recipes-mediacenter/kodi/kodi_17.0.bb
Add upstream changes from https://github.com/openembedded/meta-openembedded/commit/ab4369c5841e7f87bdc52aa8a67363c4e6524211
> kodi: add upstream patches

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend
put openwebif's pictures for vimastec vs1500
> added Vimastec vs1500

- meta-openpli/recipes-openpli/enigma2/enigma2.bb
Following https://github.com/OpenPLi/enigma2/commit/1f17cc09bfa38262e643592e1023e675365e5c77
> Enigma2: properly handle CRASHADDR in recipe

- meta-openpli/recipes-mediacenter/kodi/kodi/0001-Krypton-V3D-support.patch
- meta-openpli/recipes-mediacenter/kodi/stb-kodi-osmega_17.0.bb
Since we are using the same BSP layer for OpenPLi 4 and OpenPLi Next it's hard to add the recipe only to BSP, beucase it will fail when Building for OpenPLi 4. So move the recipe into kodi folder.
> kodi: add recipe for osmega

- meta-openpli/recipes-core/glib-networking/files/Find_CA_bundle_file_in_configure.patch
- meta-openpli/recipes-core/glib-networking/files/OpenSSL_Support_SNI_TLS_Extension.patch
- meta-openpli/recipes-core/glib-networking/glib-openssl_2.50.1.bb
Both patches waiting for upstream inclusion.
More info:
https://forums.openpli.org/topic/37567-full-ci-support/page-7#entry691229
https://forums.openpli.org/topic/37567-full-ci-support/page-8#entry691337
> glib-openssl: fix ca-certificates and SNI

- meta-openpli/recipes-multimedia/exteplayer3/exteplayer3_git.bb
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0001-set-iptv-download-timeout-0-to-disable-ifdsrc.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0002-use-getopt-added-possibility-to-set-custom-sinks.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0003-fix-buffer-duration-buffer-size-and-ring-buffer-size.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0004-rename-stored-sink-to-dvbSink-for-clarity.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0005-added-basic-support-for-plain-text-embedded-subtitle.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0006-allow-re-filling-of-audio-subtitle-tracks.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0007-re-enable-updating-video-track-info-from-dvb-video-d.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0008-first-flush-then-change-track.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0009-try-to-get-PTS-from-video-sink-first.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0010-fix-framerate-calculation.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer/0011-increase-eos-fix-timeout-to-10s.patch
- meta-openpli/recipes-multimedia/gstplayer/gstplayer_0.1.bb
- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb
- meta-openpli/recipes-support/uchardet/uchardet_0.0.6.bb
Recipes added exteplayer3, gstplayer, serviceapp, uchardet
Thanks @samsamsam-iptvplayer, @mx3L and all others
> Add several recipes used by iptvplayer

- meta-openpli/conf/distro/openpli.conf
- meta-openpli/recipes-extended/wget/wget_1.18.bbappend
Change wget back to OpenSSL in order to reduce depends installed on image
> Use OpenSSL for wget

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb
The develop branch is following recent sigc++ changes made in E2
> serviceapp: switch to develop branch

- meta-openpli/conf/distro/reporefs.conf
- meta-openpli/recipes-extended/blindscan-s2/blindscan-s2.bb
- meta-openpli/recipes-extended/blindscan-s2/blindscan-s2/support-enigma2.patch
The blindscan-s2 it a utility that is possible to blindscan dvb-s(2) satellites using stv090x devices.
> Add blindscan-s2 recipe

- meta-openpli/recipes-multimedia/astra-sm/astra-sm_0.2.bb
This prevents astra.conf overwritten during upgrade
> astra-sm: add astra.conf to CONFFILES_${PN}

- meta-openpli/recipes-core/busybox/busybox/0001-unzip-prevent-attacks-via-malicious-filenames.patch
- meta-openpli/recipes-core/busybox/busybox_1.22.1.bbappend
More info: https://forums.openpli.org/topic/51029-very-important-security-issue/
Thanks @samsamsam-iptvplayer
> busybox unzip: prevent attacks via malicious filenames

- meta-openpli/recipes-multimedia/libdvdread/libdvdread.bb
https://github.com/mirror/libdvdread/commit/d056043f4ba26944163c404421077ebfe3c8c60f
> libdvdread: bump to version 5.90.0

- meta-openpli/recipes-openpli/enigma2/enigma2.bb
Intruduced in previus commit.
Sorry! :(
> enigma2: change deprecated base_contains to bb.utils.contains

- meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-lcd4linux.bb
Please merge after merging https://github.com/eriksl/enigma2-plugin-extensions-lcd4linux-ihad-source-copy/pull/3
> lcd4linux: update PV to 4.9-r0

- meta-openpli/recipes-openpli/enigma2/settings-autorestore/settings-restore.sh
btw - should not be changed PV there in settings-autorestore.bb ?
> try remove samba.conf.tmp with redirect error instead use condition

- meta-openpli/conf/distro/openpli.conf
We need directfb feature in order to build webkit (hbbtv).
> openpli: enable directfb to distro features

- meta-openpli/conf/distro/reporefs.conf
- meta-openpli/recipes-multimedia/exteplayer3/exteplayer3_git.bb
- meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/000001_add_dash_demux.patch
This commit updates exteplayer3 to version 35 and updates ffmpeg dash demux with support for youtube dash format.
Thanks @samsamsam-iptvplayer
> exteplayer: update to v35 ffmpeg: update dash demux

- meta-openpli/recipes-core/sysfsutils/sysfsutils_2.1.0.bbappend
- meta-openpli/recipes-graphics/directfb/directfb_1.7.7.bbappend
Required in order to build webkit-hbbtv
> Allow native build of sysfsutils and directfb
