meta-dream/recipes-bsp/drivers/dreambox-boot-progress.bb

Fixes bitbake warning: ('S') don't exist, you must set 'S' to a proper value

meta-dream: dreambox-boot-progress: set proper S value

---

meta-openpli/recipes-multimedia/tuxbox/tuxbox-common.bb

Enigma use own timezone.xml in /usr/share/enigma2.
Why there a need for different in /etc?
It only leads unnecessary confusion.

Remove timezone.xml from tuxbox-common

---

meta-openpli/recipes-core/busybox/busybox_1.24.%.bbappend

This fix busybox package update.
It looks like the trick with sh copying in tmp does not work.
update-alternatives is bash script that link to /bin/sh, and after update-alternatives remove /bin/sh, it stops working.
Link to /bin/sh already exists in the package, there is no need to create it, if remove it from the busybox.links.nosuid, it is not used in update-alternatives and not removed when run update-alternatives --remove.

Remove sh from busybox.links.nosuid

---

meta-openpli/recipes-connectivity/samba/samba_4.%.bbappend

To fix startup I move sockets-dir from /run/samba to /run.
Perhaps therefore do_install now wants to remove the directory /run/samba which no longer exists.
I added an empty directory to avoid error.
Perhaps reason is a another changes on openembedded, but in any case this fix samba building.

samba4: on install add directory /run/samba to fix building

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins.bb

I can not find any plugin which currently have used anything from gstreamer.
Therefore, remove this.
This pull request should be used together with this: https://github.com/OpenPLi/enigma2-plugins/pull/47

enigma2-plugins: remove gstreamer support

---

meta-dream/conf/machine/include/dreambox-jffs2.inc
meta-dream/conf/machine/include/dreambox-ubi.inc
meta-dream/recipes-bsp/linux/linux-dreambox.inc
meta-openpli/classes/image_types_nfi.bbclass

-Build images dreamboxes fail due to changes of rootfs/image process in OE-core,IMAGE_FSTYPE need to be adapt to work with it.
-Remove unused code.
Thanks to Alexvrs.

Meta-dream: change image_fstype.

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-blurayplayer.bb

This is necessary to use a separate plugin version after its integration in enigma MovieSelection.
This plugin version does not have unnecessary screen BlurayPlayerDirBrowser.
Please use together with this pull request in enigma: https://github.com/OpenPLi/enigma2/pull/223

Plugin blurayplayer: change to branch openpli

---

meta-openpli/recipes-linux/linux-firmwares/firmware-xc5000.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/dvb-usb-drivers-meta.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-atsc-usb-hauppauge.bb

This commit adds support for Hauppauge WinTV-HVR Tuners.
The required xc5000 firmware was added also.

add atsc-usb-hauppauge meta package

---

meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb
meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend

Since googlecode was gone.
Also fix warnings when bulding OWIF due to mix of spaces and tabs introduces on a8fc9b9

python-mutagen: change SRC_URI to a valid one location

---

meta-openpli/recipes-devtools/binutils/binutils-cross_2.27.bbappend
meta-openpli/recipes-devtools/binutils/binutils_2.27.bbappend
meta-openpli/recipes-devtools/binutils/files/1001-do-not-set-the-ABIVERSION-to-5-for-MIPS.patch

https://lists.debian.org/debian-mips/2016/08/msg00011.html
This fix for example error in ffmpeg
error while loading shared libraries: /usr/lib/libavformat.so.57: ELF file ABI version invalid

Binutils: add 1001-do-not-set-the-ABIVERSION-to-5-for-MIPS.patch

---

meta-dream/conf/machine/dm500hd.conf
meta-dream/conf/machine/dm800se.conf
meta-dream/conf/machine/include/dreambox.inc
meta-dream/recipes-bsp/linux/linux-dreambox.inc

meta-dream: do not install samba on machines with small flash
The dm800se/dm500hd machines flash is too small to fit samba4.
Do not install it by default on the image.
base_contains is deprecated, please use bb.utils.contains instead
sed -i 's/base_contains/bb.utils.contains/g' `grep -r -l base_contains meta-dream/`

meta-dream: fixes for master-next

---

meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.8.2.bbappend
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.8.2.bbappend

Since we switched to new OE the gstreamer was missing few bad and ugly plugins.
Enable missing plugins using bbappend.

gstreamer: add few missing plugins

---

meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.8.2.bbappend
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.8.2.bbappend

It seems += in PACKAGECIONFIG clears the default weak assignment ??=.
So use _append that does not clear the default weak assignment.

gstreamer: use _append instead of += in PACKAGECONFIG

---

meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb

The python-mutagen recipe set SRC_URI[md5sum] using a variable which doesn't
seem to be correctly evaluated, resulting in this kind of error message
during source fetching:
ERROR: Fetcher failure for URL: <blah...>
Checksum mismatch!
File: '/home/foobar/openpli-oe-core/sources/mutagen-1.18.tar.gz' has md5
checksum 0c2cd954e4bacd79fadd45afc4acce4c when ${MD5SUM} was expected
This breaks the vuduo2 build for me.  Fix by expressing the md5sum as a
string literal where it is used.

meta-openpli: fix python-mutagen md5 checksum failure on download

---

meta-openpli/recipes-openpli/enigma2/enigma2.bb

This allow use libudfread to play bluray iso files without mount.
Please use together with this pull request: https://github.com/OpenPLi/enigma2/pull/494

Add libudfread in enigma2 depends

---

meta-openpli/recipes-support/libbluray/libbluray_git.bb

On meta-openembedded gitpkgv does not work using "gitsm://" before this commit
https://github.com/openembedded/meta-openembedded/commit/22004e5281a913818a94bcd160ad3135a9ecd314
This set package version manualy.
Remove this after meta-openembedded update.

libbluray: fix package version

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend

The purpose of enigma2-plugin-extensions-openwebif-vxg is to provide WebTV support in Chrome.
However, it's 1.4 MB in size, too much for boxes with small flash, so WebTV was coded with VXG as **optional** feature.
If -vxg is missing, there is no WebTV support for Chrome, but no other consequences.
NOTE: Try ASAP after merging, I have no OpenPLi build-env.

[OpenWebif] Split out package openwebif-vxg

---

meta-openpli/recipes-devtools/python/python-ipaddress_1.0.17.bb
meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb

Add missing python-ipaddress_1.0.17.bb file.
Add python-pip on feed which is used in python-ipaddres dependencies.

Fix python-ipaddress building

---

meta-openpli/recipes-daemons/autofs/autofs/99_autofs
meta-openpli/recipes-daemons/autofs/autofs_5.1.%.bbappend

autofs don't work without the directory and it cannot create
the directory by itself.

Create /media/net directory on every boot

---

meta-openpli/recipes-multimedia/astra-sm/astra-sm/astra-sm
meta-openpli/recipes-multimedia/astra-sm/astra-sm/astra.conf
meta-openpli/recipes-multimedia/astra-sm/astra-sm_0.2.bb

Also start astra-sm as a service with an empty config file.
Eg. astra-sm can be used as udpxy alternative.

astra-sm: update to version with t2mi everywhere

---

meta-openpli/recipes-extended/ofgwrite/ofgwrite.bb

Fix problems with 4TB disk on boxes using eMMC.
Used fdisk -l aborted because it couldn't read partitions
of that disk.

Update to latest ofgwrite version 3.7.5

---

meta-openpli/recipes-extended/ofgwrite/ofgwrite.bb

This version is needed to flash backups on hd51 via backup suite

Update to ofgwrite 3.8.0

---

meta-openpli/recipes-openpli/enigma2/enigma2.bb
meta-openpli/recipes-openpli/images/openpli-enigma2-image.bb

enigma2: use --with-7segment also for receivers with 7seg in MACHINE_FEATURES
This allow use skin_text_7segment.xml aslo for edision, spycat and formuler if they do not use their skin_text.xml.
Tested only on formuler f3 but should work on all receivers with 7 segment display.
Remove plugin vfdcontrol from image
Remove enigma2-plugin-systemplugins-vfdcontrol if 7seg in OPENPLI_FEATURES.
In manufacturers bsp is not used 7seg in OPENPLI_FEATURES.
7seg is used in the MACHINE_FEATURES and for it now is used skin_text_7segment.xml.
Therefore, remove this option which is not used anywhere.

Update for 7 segment displays

---

meta-openpli/recipes-devtools/python/python-wifi_0.5.0.bb
meta-openpli/recipes-multimedia/cdparanoia/cdparanoia_svn.bb

This patch solves the following warnings reported by futuner OE versions:
WARNING: LICENSE_python-wifi-examples includes licenses (GPLv2+) that are not listed in LICENSE
WARNING: LICENSE_libcdparanoia includes licenses (LGPLv2.1) that are not listed in LICENSE

Fix license warnings reported in future OE versions

---

meta-openpli/recipes-multimedia/tuxtxt/tuxtxt-enigma2.bb

Delete pyc leftovers in order to silence the following warning.
WARNING: tuxtxt-enigma2-2.0+gitAUTOINC+a1b42559e8-r3 do_package: QA Issue: tuxtxt-enigma2: Files/directories were installed but not shipped in any package:
/usr/lib/enigma2/python/Plugins/Extensions/Tuxtxt/__init__.pyc
/usr/lib/enigma2/python/Plugins/Extensions/Tuxtxt/plugin.pyc

tuxtxt-enigma2: fix warning about not shipped pyc files

---

meta-dream/recipes-bsp/linux/linux-dreambox.inc

Since commit:
http://git.openembedded.org/openembedded-core/commit/meta/classes/kernel.bbclass?h=morty&id=a248ef51ae680e81cf78f07fe242ac6e01a5fcb4
vmlinux is not incluced in image.
Which result in a non bootable box after a flash.
Set files to vmlinux to restore it.

dmm: Fix non bootable box.

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-subssupport_1.5.5.bb

subssupport is enigma2 plugin which provides improved subtitles support for several enigma2 plugins.
It can also be used as standalone plugin, since it provides subtitles downloader and dvb subtitles player.
Plugins which use or used subssupport: archivCZSK, TSMedia, MediaPlayer2, EMC with Subssupport
Also kodiext uses subssupport.

Add SubsSupport Plugin

---

meta-openpli/recipes-mediacenter/kodi/kodi.inc

In enable_glew remove tabs and switch to spaces in order to prevent
warning "Variable enable_glew contains tabs, please remove these"
Handle missing space in EXTRA_OECONF_append
Add few upstream changes from https://github.com/openembedded/meta-openembedded/commit/ab4369c5841e7f87bdc52aa8a67363c4e6524211

kodi: update recipe with changes from meta-openembedded

---

meta-openpli/recipes-core/glib-networking/glib-networking_2.%.bbappend
meta-openpli/recipes-core/glib-networking/glib-openssl_2.50.1.bb

The gnutls is much, much slower than OpenSSL, switch to new glib-openssl TLS backend.
More info: https://forums.openpli.org/topic/37567-full-ci-support/page-7#entry688949

glib-networking: use glib-openssl for TLS backend

---

meta-openpli/conf/distro/openpli.conf

Change PACKAGECONFIG for curl and openldap to make use of OpenSSL instead of GnuTLS.
It reduces the image size (almost 2MB) and most probably the compile time, since GnuTLS might not build anymore, at least on base instalation.

Use OpenSSL for curl and openldap

---

meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-af9015.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-af9035.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-dib0700.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-it913x.bb

Update several dvb-usb drivers for newer kernels. 
Switch provider to kernel (we do not build v4l drivers since OpenPLi 3). 
Inherit allarch to create packages once.

dvb-usb: update for newer kernels

---

meta-openpli/recipes-openpli/enigma2-dvb-drivers/dvb-usb-drivers-meta.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-ct2-dvb-usb-pctv292e.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-as102.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-dtt200u.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-em28xx.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-pctv452e.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-rtl2832.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-siano.bb

Update several dvb-usb drivers for newer kernels.
Switch provider to kernel (we do not build v4l drivers since OpenPLi 3).
Inherit allarch to create packages once.
Also provide recipe for pctv292e.

dvb-usb: update for newer kernels 

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend

It seems that D, PLUGINPATH and MACHINE didn't expand any more, so the resulting ipk
was getting images for all OWIF supported machines. Using d.getVar variables work again
in python code block.
Also the python code block was change into do_cleanup task instead of appending the cleanup
code block to other tasks.

OWIF: change code into task and expand variables with d.getVar

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-modifyplifullhd.bb
meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-refreshbouquet.bb

We don't need to depend on enigma2 becase every time the enigma2 rebuilds
it will cause modifyplifullhd to rebuild.
Also stop replacing/conficting with old plugin name. It's long gone.

modifyplifullhd: allarch do not depend on enigma2

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-lcd4linux.bb

When using allrch it seems that depending on packages that chang between arch causes
rebuilds on plugins. Change depends into rdepends to solve issue.

lcd4linux: change DEPENDS into RDEPENDS

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-lcd4linux.bb

Although we can depend on libusb, in runtime nothing provides libusb.
Remove it to allow building and restore the required runtime dependency if any.

lcd4linux: nothing provides libusb in runtime remove it

---

meta-dream/recipes-bsp/drivers/dreambox-dvb-modules.inc

No need to install license file.
This prevent warning:
WARNING: dreambox-dvb-modules-dm8000-3.2-20140604a-r7.0 do_package: QA Issue: dreambox-dvb-modules-dm8000:
Files/directories were installed but not shipped in any package:
/lib/modules/3.2-dm8000/extra/LICENSE
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
dreambox-dvb-modules-dm8000: 1 installed and not shipped files. [installed-vs-shipped]

dmm: get rid of warning dvb-modules

---

meta-openpli/recipes-openpli/enigma2-dvb-drivers/dvb-usb-drivers-meta.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/dvb-usb-drivers-meta.inc
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-atsc-usb-hauppauge-950q.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-atsc-usb-hauppauge-955q.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-atsc-usb-hauppauge.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-ct2-dvb-usb-pctv292e.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-ct2-usb-dvbsky-t330.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-ct2-usb-geniatech-t230.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-af9015.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-af9035.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-as102.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-dib0700.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-dtt200u.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-dw2102.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-em28xx.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-it913x.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-pctv452e.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-rtl2832.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-siano.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-tbs.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-technisat-skystar.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-s2-usb-dvbsky-s960.bb

Create dvb-usb-drivers-meta.inc and move common parts.
Also don't create dev/dbg packages.
Finally disable tasks not required to create those packages.

dvb-usb-meta: move common parts in a single include file

---

meta-openpli/recipes-multimedia/gstplayer/gstplayer_0.1.bb

It fixes the following warning:
WARNING: gstplayer-0.1-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: '/.../armv7ahf-neon-oe-linux-gnueabi/gstplayer/0.1-r0/packages-split/gstplayer/usr/bin/gstplayer' [ldflags]

gstplayer: add LDFLAGS when building

---

meta-openpli/recipes-multimedia/readymedia/readymedia.bb

Fixes the following warnings:
readymedia-1.1.0+gitAUTOINC+5450ac486e: readymedia rdepends on libjpeg-turbo, but it isn't a build dependency, missing libjpeg-turbo in DEPENDS or PACKAGECONFIG? [build-deps]
readymedia-1.1.0+gitAUTOINC+5450ac486e: readymedia rdepends on libvorbis, but it isn't a build dependency, missing libvorbis in DEPENDS or PACKAGECONFIG? [build-deps]
readymedia-1.1.0+gitAUTOINC+5450ac486e: readymedia rdepends on libflac, but it isn't a build dependency, missing flac in DEPENDS or PACKAGECONFIG? [build-deps]
readymedia-1.1.0+gitAUTOINC+5450ac486e: readymedia rdepends on libid3tag, but it isn't a build dependency, missing libid3tag in DEPENDS or PACKAGECONFIG? [build-deps]
readymedia-1.1.0+gitAUTOINC+5450ac486e: readymedia rdepends on libsqlite3, but it isn't a build …

readymedia: add missing depends

---

meta-openpli/recipes-multimedia/gstplayer/gstplayer_0.1.bb

It seems that after https://github.com/OpenPLi/openpli-oe-core/commit/c59385c4609b2e431692465a6c6bfce3fff18cd2 the serviceapp fails to locate gstplayer.
So with gstplayer IPTVPlayer works, with gstplayer_gst-1.0 serviceapp works.
With simlink hopefully both will work.

gstplayer: add simlink to gstplayer_gst-1.0

---

meta-openpli/recipes-multimedia/libdvbsi++/files/nit.patch
meta-openpli/recipes-multimedia/libdvbsi++/libdvbsi++_0.3.8.bb

Patch was submited to libdvbsi++ author for inclusion.
Until then include patch to allow reading network_id from Enigma2.

libdvbsi: store network_id from NIT section

---

meta-openpli/recipes-support/libbluray/libbluray_git.bb

This prevents warning:
WARNING: libbluray-v1.0.0+gitAUTOINC+da27917598-r0 do_configure: QA Issue:
libbluray: configure was passed unrecognised options: --disable-bdjava [unknown-configure-option]
http://git.videolan.org/?p=libbluray.git;a=commit;h=415da3663a1ff2a935d4a36417f4f46bf2b947d2

libbluray: remove unrecognised configure option

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb

Any package that depends on arch that has MACHINE_ARCH (like enigma2)
will force rebuild every time MACHINE changes.
Change serviceapp to MACHINE_ARCH to build once for every MACHINE
without getting version going backwards on every build.

serviceapp: change PACKAGE_ARCH to MACHINE_ARCH

---

meta-openpli/recipes-support/libbluray/libbluray_git.bb

We are beyond that commit in meta-openembedded and git head is version 1.0.0 now.

libbluray: bump to version 1.0.0

---

meta-openpli/recipes-connectivity/pyload/pyload.bb
meta-openpli/recipes-multimedia/dvbtools/wscan_20170107.bb
meta-openpli/recipes-support/libev/libev_4.24.bb

This will make the develop branch of openpli-oe-core build openpli-enigma2-feed again from scratch.
- Update libev to 4.24 (4.23 doesn't exist anymore on the server)
- Update w_scan to 20170107 (20161022 doesn't exist anymore on the server)
- Update the URL for pyload-src-v0.4.9.zip. (github doesn't host it anymore for some reason so let's use the openelec.tv mirror)

Fix some URLs

---

meta-openpli/conf/distro/reporefs.conf
meta-openpli/recipes-linux/linux-firmwares/firmware-dvb-demod-mn88473-01.bb
meta-openpli/recipes-openpli/enigma2-dvb-drivers/enigma2-plugin-drivers-dvb-usb-rtl2832.bb

Required for Astrometa T2 devices.
More info: https://forums.openpli.org/topic/35710-astrometa-dvb-tt2c-mn88472mn88473/page-5

dvb-usb: add mn88473 firmware

---

meta-openpli/recipes-multimedia/mpg123/mpg123_1.23.%.bbappend

To prevent warning:
mpg123-1.23.6-r0 do_package_qa: QA Issue: mpg123 rdepends on libltdl, but it isn't a build dependency,
missing libtool in DEPENDS or PACKAGECONFIG? [build-deps]

mpg123: silence mpg123 rdepends on libltdl warning

---

meta-dream/recipes-bsp/drivers/dreambox-blindscan-utils_1.9.bb

To prevent warning:
WARNING: dreambox-blindscan-utils-1.9-r0 do_package: QA Issue: File '/usr/bin/blindscan' from dreambox-blindscan-utils
was already stripped, this will prevent future debugging! [already-stripped]

dreambox-blindscan-utils: silence already stripped warning

---

meta-openpli/recipes-multimedia/libdvdnav/libdvdnav.bb

git head is version 5.0.4, not 5.0.2.
https://github.com/mirror/libdvdnav/commit/c9651ff16663d039b2fdf4a5989c5eea35919c2e

libdvdnav: bump to version 5.0.4

---

meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-libav.inc
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-libav_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad.inc
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base.inc
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0.inc
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0_git.bb

- gstreamer1.0 depends on elfutils
- Remove unused configure flags
- clean remaining unused parameters
- inherit gtk-doc like in upstream

Gstreamer 1.12.0 fix remaining build warnings:

---

meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base/subparse-avoid-false-negatives-dealing-with-UTF-8.patch
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_git.bb

More info: https://bugzilla.gnome.org/show_bug.cgi?id=740784

gstreamer: subparse: avoid false negatives dealing with UTF-8

---

meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/000001_add_dash_demux.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/000003_allow_to_choose_rtmp_impl_at_runtime.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/ffmpeg-aac.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/ffmpeg-buffer-size.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/ffmpeg-fix-edit-list-parsing.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/ffmpeg-fix-hls.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/ffmpeg-fix-mpegts.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/mips64_cpu_detection.patch
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg_3.%.bbappend
meta-openpli/recipes-multimedia/ffmpeg/ffmpeg_3.3.bb
meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-serviceapp.bb

Thanks to SSS, mx3L and Taapat for making it possible.
FFMpeg:
- Update to ffmpeg 3.3 recipe from upstream oe
- Initial support for mpeg-dash streams
- aac and buffersize patches from duckbox developers
- fixes for hls and mpegts
- Taapat: disable log to fix freezing on edit list parsing
- samsamsam: Allow exteplayer3 to select between ffmpeg internal rtmp or external librtmp support
- mips64_cpu_detection.patch from upstream oe
- Adapt bbappend based for ffmpeg 3.3
ServiceApp:
- Add exteplayer3 and gstplayer to RRECOMMENDS_${PN} so they get installed as well.

Update ffmpeg to 3.3 and adapt for exteplayer3

---

meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-youtube.bb

In the plugin has no direct openpssl import, but it is necessary when using twisted-web for https links

Plugin youtube: add python-pyopenssl in rdepends

---

meta-openpli/recipes-multimedia/exteplayer3/exteplayer3_git.bb

exteplayer3 not use ffmpeg but its libraries, which are added automatically.

Remove ffmpeg from exteplayer3 rdepends

---

meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-common.inc
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-libav_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_git.bb
meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0_git.bb

This allows on the update or on corrections perform them in a single file, rather than make the same changes in many files, which can lead to inadvertent errors.

Gstreamer: move the duplicate code into one file

---

meta-openpli/recipes-multimedia/ffmpeg/ffmpeg_3.%.bbappend

Remove not existing provides and packages.
Remove not used libtheora and libvpx encoders.
Remove unnecessary in depends, the rest check packageconfig.
Remove unnecessary rdepends. All necessary package dependencies are set automatically.

Ffmpeg cleanup

---

meta-openpli/recipes-openpli/enigma2/enigma2.bb

This allow use skin_text_7segment.xml aslo for edision, spycat and formuler if they do not use their skin_text.xml.
Tested only on formuler f3 but should work on all receivers with 7 segment display.
This commit dublicate https://github.com/OpenPLi/openpli-oe-core/commit/4782aecd8c2fc51d742a0be24905e1df3e4ab5b5
Whitch is lost after the merge.

enigma2: use --with-7segment also for receivers with 7seg in MACHINE_FEATURES

---

meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/000001_add_dash_demux.patch

- add support for live streams which need manifest refresh (with segment list update)
- reset context after each segment to free indexes from previously processed segments
- dash-demux: small improvements for live streams with profile:isoff-live:2011
- Changed to build against ffmpeg 3.3

New version of dash demux patch by SSS:

---

meta-openpli/recipes-connectivity/nfs-utils/nfs-utils_1.%.bbappend

The nfs-utils-client doesn't really require bash in order to work. As the bbappend mentions in comments.
The nfs-utils requires bash due to osd_login. Until somebody patches the osd_login to use sh, use original depends from open-embedded that already include bash.
~ opkg files nfs-utils-client | grep "/" | xargs fgrep "/bin/bash"
~ opkg files nfs-utils-client | grep "/" | xargs fgrep "/bin/sh"
/etc/init.d/nfscommon:#!/bin/sh
/usr/sbin/start-statd:#!/bin/sh
~ opkg files nfs-utils | grep "/" | xargs fgrep "/bin/bash"
/sbin/osd_login:#!/bin/bash
~ opkg files nfs-utils | grep "/" | xargs fgrep "/bin/sh"
/etc/init.d/nfsserver:#!/bin/sh
Please note that by default we do not install nfs-utils, so most probably the wrongly installed bash will go way and that might have undesired behaviour.

nfs-utils: properly silence the bash provider not found

---

meta-openpli/recipes-daemons/autofs/autofs_5.1.%.bbappend

Same for auto.net file (created as example), if some user using it as one file with params for mountpoint

autofs auto.master file as CONFFILES

---

meta-openpli/recipes-connectivity/samba/samba_4.%.bbappend

If the user has changed smb.conf, this allow save user smb.conf on package update.

samba: add smb.conf in conffiles

---

meta-openpli/recipes-extended/blindscan-s2/blindscan-s2/support-enigma2.patch

Optional gcc compiler in makefile was merged upstream.
Update patch to make build system happy again.

blindscan-s2: udate enigma2 support patch

---

meta-openpli/recipes-multimedia/gstplayer/gstplayer_0.1.bb

In https://github.com/OpenPLi/openpli-oe-core/commit/d23e4f19355c9d4f86ae62d9b80009647000ebf2 added postinst script witch create simlink to gstplayer_gst-1.0.
But on the package remove this symlynk is not removed and remains.
This causes an error on each package update:
Configuring gstplayer.
ln: /usr/bin/gstplayer_gst-1.0: File exists
Collected errors:
* pkg_run_script: package gstplayer postinst script returned status 1.
* opkg_configure: gstplayer.postinst returned 1.
Add prerm script witch remove symlynk on package remove
and fix this error.
Also remove unnecessary variable  in postinst script.

gstplayer: remove gstplayer_gst-1.0 simlink on package remove

---

meta-openpli/recipes-extended/ofgwrite/ofgwrite.bb

The PV by default has value 1.0 if we dont override it.
That causes the ofgwrite not to get updated when using AUTOREV.

ofgwrite: fix PV to allow updates

---

meta-openpli/recipes-multimedia/ffmpeg/ffmpeg/000001_add_dash_demux.patch

Use patch from @fairbird because the one from @samsamsam-iptvplayer didn't apply nicely on ffmpeg 3.3
https://forums.openpli.org/topic/41198-serviceapp-gstplayer-and-exteplayer3/page-32#entry752827
Fixes patch from https://github.com/OpenPLi/openpli-oe-core/commit/b56e17698a97f28feeebdb961a47ac23c0fd51f4

ffmpeg: update dash demux patch

---

meta-openpli/recipes-devtools/elfutils/elfutils-0.168/0001-build-Provide-alternatives-for-glibc-assumptions-hel.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/0001-elf_getarsym-Silence-Werror-maybe-uninitialized-fals.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/0001-fix-a-stack-usage-warning.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/0001-remove-the-unneed-checking.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/Fix_one_GCC7_warning.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/aarch64_uio.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/0001-Ignore-differences-between-mips-machine-identifiers.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/0002-Add-support-for-mips64-abis-in-mips_retval.c.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/0003-Add-mips-n64-relocation-format-hack.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/arm_backend.diff
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/hppa_backend.diff
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/hurd_path.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/ignore_strmerge.diff
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/kfreebsd_path.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/mips_backend.diff
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/mips_readelf_w.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/debian/testsuite-ignore-elflint.diff
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/fallthrough.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/fixheadercheck.patch
meta-openpli/recipes-devtools/elfutils/elfutils-0.168/shadow.patch
meta-openpli/recipes-devtools/elfutils/elfutils/Fix_elf_cvt_gunhash.patch
meta-openpli/recipes-devtools/elfutils/elfutils/dso-link-change.patch
meta-openpli/recipes-devtools/elfutils/elfutils_0.168.bb
meta-openpli/recipes-devtools/gcc/files/ubsan-fix-check-empty-string.patch
meta-openpli/recipes-devtools/gcc/gcc-source_6.%.bbappend

Tested on a clean installation of Fedora 26 using a clean build-directory
- Upgrade libelf from 0.166 to 0.168 (upstream OE)
- Backport upstream OE gcc patch
Tested from a clean state (no build directory) for zgemma h2h (mipsel) and the Mutant HD51 (arm)
Both images build without errors and work perfectly fine.

Fix building OpenPLi with gcc 7
